"use strict";function archiveOpen(file_name,array_buffer){var archive_type=null;if(isRarFile(array_buffer)){archive_type='rar';}else if(isZipFile(array_buffer)){archive_type='zip';}else if(isTarFile(array_buffer)){archive_type='tar';}else{return null;}
var handle=null;var entries=[];switch(archive_type){case 'rar':handle=_rarOpen(file_name,array_buffer);entries=_rarGetEntries(handle);break;case 'zip':handle=_zipOpen(file_name,array_buffer);entries=_zipGetEntries(handle);break;case 'tar':handle=_tarOpen(file_name,array_buffer);entries=_tarGetEntries(handle);break;}
entries.sort(function(a,b){if(a.name<b.name)return-1;if(a.name>b.name)return 1;return 0;});return{file_name:file_name,archive_type:archive_type,array_buffer:array_buffer,entries:entries,handle:handle};}
function archiveClose(archive){archive.file_name=null;archive.archive_type=null;archive.array_buffer=null;archive.entries=null;archive.handle=null;}
function _rarOpen(file_name,array_buffer){var rar_files=[{name:file_name,size:array_buffer.byteLength,type:'',content:new Uint8Array(array_buffer)}];return{file_name:file_name,array_buffer:array_buffer,password:null,rar_files:rar_files};}
function _zipOpen(file_name,array_buffer){var zip=new JSZip(array_buffer);return{file_name:file_name,array_buffer:array_buffer,password:null,zip:zip};}
function _tarOpen(file_name,array_buffer){return{file_name:file_name,array_buffer:array_buffer,password:null};}
function _rarGetEntries(rar_handle){var info=readRARFileNames(rar_handle.rar_files,rar_handle.password);var entries=[];Object.keys(info).forEach(function(i){var name=info[i].name;var is_file=info[i].is_file;entries.push({name:name,is_file:info[i].is_file,readData:function(cb){if(is_file){readRARContent(rar_handle.rar_files,rar_handle.password,name,cb);}else{cb(null);}}});});return entries;}
function _zipGetEntries(zip_handle){var zip=zip_handle.zip;var entries=[];Object.keys(zip.files).forEach(function(i){var zip_entry=zip.files[i];var name=zip_entry.name;var is_file=!zip_entry.dir;entries.push({name:name,is_file:is_file,readData:function(cb){if(is_file){var data=zip_entry.asArrayBuffer();cb(data);}else{cb(null);}}});});return entries;}
function _tarGetEntries(tar_handle){var tar_entries=tarGetEntries(tar_handle.file_name,tar_handle.array_buffer);var entries=[];tar_entries.forEach(function(entry){var is_file=true;entries.push({name:entry.name,is_file:is_file,readData:function(cb){if(is_file){var data=tarGetEntryData(entry,tar_handle.array_buffer);cb(data.buffer);}else{cb(null);}}});});return entries;}
function isRarFile(array_buffer){var rar_header1=[0x52,0x45,0x7E,0x5E].join(', ');var rar_header2=[0x52,0x61,0x72,0x21,0x1A,0x07,0x00].join(', ');var rar_header3=[0x52,0x61,0x72,0x21,0x1A,0x07,0x01,0x00].join(', ');if(array_buffer.byteLength<8){return false;}
var header1=new Uint8Array(array_buffer).slice(0,4).join(', ');var header2=new Uint8Array(array_buffer).slice(0,7).join(', ');var header3=new Uint8Array(array_buffer).slice(0,8).join(', ');return(header1===rar_header1||header2===rar_header2||header3===rar_header3);}
function isZipFile(array_buffer){var zip_header=[0x50,0x4b,0x03,0x04].join(', ');if(array_buffer.byteLength<4){return false;}
var header=new Uint8Array(array_buffer).slice(0,4).join(', ');return(header===zip_header);}
function isTarFile(array_buffer){var tar_header=['u','s','t','a','r'].join(', ');if(array_buffer.byteLength<512){return false;}
var header=_workingMap(new Uint8Array(array_buffer).slice(257,257+5),String.fromCharCode).join(', ');return(header===tar_header);}